[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "crm-internal"
version = "0.1.0"
dependencies = [
    "pydantic>=2.0.0"
]

[tool.setuptools.packages.find]
where = ["."]
include = ["common*"]
